package org.oe.algorithm.newant;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFramePath.java
 *
 * Created on 2013-11-28, 11:59:04
 */


import java.io.PrintStream;
import java.awt.*;

/**
 * @author 彤
 */
public class NewJFramePath extends javax.swing.JFrame {

    /**
     * Creates new form NewJFramePath
     */
    public NewJFramePath() {
        initComponents();
    }

    public void paint(Graphics g) {
        int len = Data.dataLength;
        double flavia = 25.2;
        int you = (int) flavia;

        for (int i = 0; i < len; i++) {
            g.drawString(String.valueOf(Data.data[i][0]), (int) (Data.data[i][1] * 10) / 2 + 250,
                    (int) (10 * Data.data[i][2]) / 2);
            g.drawLine((int) (10 * Data.data[ACO.bestTour[i]][1]) / 2 + 250,
                    (int) (10 * Data.data[ACO.bestTour[i]][2]) / 2, (int) (10 * Data.data[ACO.bestTour[i + 1]][1]) / 2 + 250,
                    (int) (10 * Data.data[ACO.bestTour[i + 1]][2]) / 2);
        }
        if (NewJFrame.flag == 0) g.drawString("蚁恒模型", 150, 560);
        else if (NewJFrame.flag == 1) g.drawString("传统模型", 150, 560);

        g.drawString("解路径 " + NewJFrame.route, 150, 580);
        g.drawString("解路径长度 " + ACO.bestLength, 150, 600);
        //g.drawString("更新次数"+NewJFrame.updateTimes, 150, 620);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel1.setText("ACO TSP");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup()
                                        .addContainerGap(548, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(496, 496, 496))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(621, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFramePath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    // End of variables declaration

}
